### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pine3ree** [gooodev/postcss-viewport-unit-fallback#1]
Hello, thanks for this.

Could you also make so that also the `!important` rule modifier duplicated?

```css
.some-css-class {
    min-height: 75dvh !important;
}
```
```css
.some-css-class { /* Note: this is actually the place where the fallback rule is added */
    min-height: 75vh !important; /* important is not duplicated right now */
    min-height: 75dvh !important;
}
```

Cheers!!!!
